### ISSUE TITLE
Change of License

### ISSUE THREAD

**Issue by ritisha2000** [UBC-MDS/pokehelperr#42]
For this project, we are currently using the MIT license. It's a commonly used license but it is also very permissive which makes it easier for us to share and improve our package. However, there may be drawbacks to that like anyone else can use and profit from this code. Should we consider other licenses?

**Comment by snesunil** [comment]
I believe that we can continue with the MIT license for our pokehelperr project as it is a widely used and straightforward open-source license. It will also help others to take our code as a baseline and enhance and implement more attractive features on it that can benefit everyone.

**Comment by AguilarRaul** [comment]
Given the nature of our package and how large is the Pokémon community, I think it is appropriate to use the MIT license. This gives the possibility that anyone can add more features to our package, for example a new algorithm to calculate the balances or to give a better distribution to the value of the resistances and weaknesses for each Pokémon. Personally I don't have any problem that the community can build new features or improve the existing ones, improving the usability of the package.

Furthermore, I don't have any issue with anyone profiting something based on this code or expect any royalties, just a small attribution note is good enough.

**Comment by J99thoms** [comment]
I concur.
